//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AksesuarSat_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumlarID { get; set; }
        public string YorumBaslik { get; set; }
        public string YorumIcerik { get; set; }
        public System.DateTime YorumTarih { get; set; }
        public int UrunID { get; set; }
        public int YorumUstID { get; set; }
        public Nullable<int> UyeID { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
